version: "3.8"
services:
    dev:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: dev
        tty: true
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - .:/code
        depends_on:
            - database
            - redis

    database:
        image: postgres:14
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=code_development
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:5432

    redis:
        image: redis:7
        ports:
            - 6379:6379

volumes:
    db:
