version: "3.8"
services:
    dev:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: dev
        tty: true
        stdin_open: true
        ports:
            - 8000:8000
        volumes:
            - .:/code
        depends_on:
            - database

    database:
        image: postgres:14
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=database
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    db:
